#!/bin/bash -e

# General
export SERVER_ROOT_NAME=webapps
export APPLICATION_NAME=fullstack
export PROJECT_NAME=backend
export GIT_REPO=git@github.com:stphivos/django-angular2-fullstack-devops.git
export GIT_BRANCH=master

# AWS
export REGION=$(aws configure get region)
export INSTANCE_TYPE=t2.micro
export SOURCE_AMI=ami-9cee02f3
export ROOT_DOMAIN=pstylianides.com
export ROUTE_53_ZONE_ID=Z3BXIXH96UUDRV

# Database
export DB_NAME=${APPLICATION_NAME}
export DB_USERNAME=${APPLICATION_NAME}
export DB_PASSWORD=!qwerty1
export DB_PORT=5432

# Web
export SSH_USERNAME=ubuntu
export SSH_KEY_NAME=${APPLICATION_NAME}
export SSH_PRIVATE_KEY_PATH=~/.ssh/${APPLICATION_NAME}.pem
export SSH_PUBLIC_KEY_PATH=~/.ssh/${APPLICATION_NAME}.pub
export SERVER_ROOT_PATH=/${SERVER_ROOT_NAME}
export APPLICATION_PATH=${SERVER_ROOT_PATH}/${APPLICATION_NAME}
export VIRTUALENV_PATH=${APPLICATION_PATH}/virtualenv
export PROJECT_PATH=${APPLICATION_PATH}/${PROJECT_NAME}
